# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/language-javascript/ for more details

version: 2.1
defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: cimg/openjdk:21.0.11-node
    environment:
        HUSKY: 0
        DEBUG_NITRO: true # Faster builds
        METADATA_SERVER_DETECTION: "none" # Fixes: https://github.com/googleapis/google-cloud-node/issues/7668

jobs:
    setup:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Enable corepack
                  command: sudo corepack enable
            # Download and cache dependencies
            - restore_cache:
                  name: Restore Yarn Package Cache
                  key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Install dependencies
                  command: yarn
            - run:
                  name: Install Playwright Browsers
                  command: yarn playwright install --with-deps chromium
            - save_cache:
                  name: Save Yarn packages cache
                  key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
                  paths:
                      - .yarn
                      - node_modules
                      - ~/.cache/ms-playwright
            - run:
                  name: Prepare Nuxt
                  command: yarn nuxi prepare
            - persist_to_workspace:
                  root: ~/repo
                  paths:
                      - .nuxt

    prepare:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Enable corepack
                  command: sudo corepack enable
            - restore_cache:
                  name: Restore Yarn Package Cache
                  key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Run typecheck
                  command: yarn typecheck

    static_tests:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Enable corepack
                  command: sudo corepack enable
            - restore_cache:
                  name: Restore Yarn Package Cache
                  key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Run linter & code formatting check
                  command: yarn lint

    dynamic_tests:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Enable corepack
                  command: sudo corepack enable
            - restore_cache:
                  name: Restore Yarn Package Cache
                  key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Run Unit and Component Tests
                  command: yarn test:unit
            - run:
                  name: Build Functions
                  command: yarn build:functions
            - run:
                  name: Run Firestore Rules Tests
                  command: yarn test:firestore
            # TODO: fix test performance and execution time
            # - run:
            #       name: Run Cloud Functions Tests
            #       command: yarn test:functions

    e2e_tests:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Enable corepack
                  command: sudo corepack enable
            - restore_cache:
                  name: Restore Yarn Package Cache
                  key: yarn-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Build Nuxt App
                  command: yarn build && yarn build:functions
            # TODO: fix authentication on CI env for emulator
            # - run:
            #       name: Run E2E Tests
            #       command: yarn test:e2e

workflows:
    check_workflow:
        jobs:
            - setup:
                  context: github-deploy
                  filters:
                      branches:
                          only:
                              - dev
                              - /feature\/.*/
                              - /hotfix\/.*/
            - prepare:
                  context: github-deploy
                  requires:
                      - setup
            - static_tests:
                  context: github-deploy
                  requires:
                      - prepare
            - dynamic_tests:
                  context: github-deploy
                  requires:
                      - prepare
            - e2e_tests:
                  context: github-deploy
                  requires:
                      - dynamic_tests
    release_workflow:
        jobs:
            - setup:
                  context: github-deploy
                  filters:
                      branches:
                          only:
                              - master
            - prepare:
                  context: github-deploy
                  requires:
                      - setup
            - static_tests:
                  context: github-deploy
                  requires:
                      - prepare
            - dynamic_tests:
                  context: github-deploy
                  requires:
                      - prepare
            - e2e_tests:
                  context: github-deploy
                  requires:
                      - dynamic_tests
