/**
 * Bogota faculties.
 *
 * Bogota is its own faculty for global courses.
 *
 * Comented ones have no programs
 */
export enum eSIABogotaFaculty {
	SEDE_BOGOTÁ = "2000 SEDE BOGOTÁ",
	MEDICINA = "2056 FACULTAD DE MEDICINA",
	ARTES = "2049 FACULTAD DE ARTES",
	// IBUN = "2059 INSTITUTO DE BIOTECNOLOGÍA - IBUN",
	ENFERMERÍA = "2054 FACULTAD DE ENFERMERÍA",
	INGENIERÍA = "2055 FACULTAD DE INGENIERÍA",
	// ICTA = "2063 INSTITUTO DE CIENCIA Y TECNOLOGÍA DE ALIMENTOS - ICTA",
	ODONTOLOGÍA = "2058 FACULTAD DE ODONTOLOGÍA",
	// IEPRI = "2061 INSTITUTO DE ESTUDIOS POLÍTICOS Y RELACIONES INTERNACIONALES - IEPRI",
	// IECO = "2064 INSTITUTO DE ESTUDIOS EN COMUNICACIONES - IECO",
	DERECHO = "2053 FACULTAD DE DERECHO, CIENCIAS POLÍTICAS Y SOCIALES",
	// INSTITUTO_DE_GENÉTICA = "2062 INSTITUTO DE GENÉTICA",
	// AGRONOMÍA = "2048 FACULTAD DE AGRONOMÍA",
	CIENCIAS_ECONÓMICAS = "2051 FACULTAD DE CIENCIAS ECONÓMICAS",
	CIENCIAS = "2050 FACULTAD DE CIENCIAS",
	CIENCIAS_HUMANAS = "2052 FACULTAD DE CIENCIAS HUMANAS",
	CIENCIAS_AGRARIAS = "2728 FACULTAD DE CIENCIAS AGRARIAS",
	MEDICINA_VETERINARIA = "2057 FACULTAD DE MEDICINA VETERINARIA Y DE ZOOTECNIA",
}

/**
 * Bogota global (2000) programs
 */
export enum eSIABogotaProgram {
	COMPONENTE_DE_LIBRE_ELECCIÓN = "2CLE COMPONENTE DE LIBRE ELECCIÓN",
	COMPONENTE_ELEGIBLE_POSGRADO = "2CLP COMPONENTE ELEGIBLE POSGRADO",
	CRÉDITOS_PRIMER_PLAN_PARA_DOBLE_TITULACIÓN = "2DTS CRÉDITOS PRIMER PLAN PARA DOBLE TITULACIÓN",
	PROGRAMA_DE_ELECTIVAS = "2PEL PROGRAMA DE ELECTIVAS (L)",
}

/**
 * Medicine faculty (2056) programs
 */
export enum eSIAMedicineBogotaProgram {
	FISIOTERAPIA = "2550 FISIOTERAPIA",
	FONOAUDIOLOGÍA = "2551 FONOAUDIOLOGÍA",
	MEDICINA = "2552 MEDICINA",
	NUTRICIÓN_Y_DIETÉTICA = "2553 NUTRICIÓN Y DIETÉTICA",
	TERAPIA_OCUPACIONAL = "2952 TERAPIA OCUPACIONAL",
}

/**
 * Vet. Medicine faculty (2057) programs
 */
export enum eSIAVetMedicineBogotaProgram {
	MEDICINA_VETERINARIA = "2555 MEDICINA VETERINARIA",
	// Why is there two?
	ZOOTECNIA_A = "2556 ZOOTECNIA",
	ZOOTECNIA_B = "2990 ZOOTECNIA",
}

/**
 * Enfermery faculty (2054) programs
 */
export enum eSIAEnfermeryBogotaProgram {
	ENFERMERÍA = "2540 ENFERMERÍA",
}

/**
 * Arts faculty (2049) programs
 */
export enum eSIAArtsBogotaProgram {
	ARQUITECTURA = "2506 ARQUITECTURA",
	ARTES_PLÁSTICAS = "2507 ARTES PLÁSTICAS",
	CINE_Y_TELEVISIÓN = "2508 CINE Y TELEVISIÓN",
	DISEÑO_GRÁFICO = "2509 DISEÑO GRÁFICO",
	DISEÑO_INDUSTRIAL = "2510 DISEÑO INDUSTRIAL",
	MÚSICA = "2511 MÚSICA",
	MÚSICA_INSTRUMENTAL = "2512 MÚSICA INSTRUMENTAL",
}

/**
 * Engineering faculty (2055) programs
 */
export enum eSIAEngineeringBogotaProgram {
	INGENIERÍA_AGRÍCOLA = "2541 INGENIERÍA AGRÍCOLA",
	INGENIERÍA_CIVIL = "2542 INGENIERÍA CIVIL",
	INGENIERÍA_ELECTRÓNICA = "2545 INGENIERÍA ELECTRÓNICA",
	INGENIERÍA_INDUSTRIAL = "2546 INGENIERÍA INDUSTRIAL",
	INGENIERÍA_MECÁNICA = "2547 INGENIERÍA MECÁNICA",
	INGENIERÍA_MECATRÓNICA = "2548 INGENIERÍA MECATRÓNICA",
	INGENIERÍA_QUÍMICA = "2549 INGENIERÍA QUÍMICA",
	INGENIERÍA_ELÉCTRICA = "2983 INGENIERÍA ELÉCTRICA",
	// Why is there two?
	INGENIERÍA_DE_SISTEMAS_Y_COMPUTACIÓN_A = "2879 INGENIERÍA DE SISTEMAS Y COMPUTACIÓN",
	INGENIERÍA_DE_SISTEMAS_Y_COMPUTACIÓN_B = "2A74 INGENIERÍA DE SISTEMAS Y COMPUTACIÓN",
}

/**
 * Odontology faculty (2058) programs
 */
export enum eSIAOdontologyBogotaProgram {
	ODONTOLOGÍA = "2557 ODONTOLOGÍA",
}

/**
 * Law faculty (2053) programs
 */
export enum eSIALawBogotaProgram {
	CIENCIA_POLÍTICA = "2538 CIENCIA POLÍTICA",
	DERECHO = "2539 DERECHO",
}

/**
 * Science faculty (2050) programs
 */
export enum eSIAScienceBogotaProgram {
	BIOLOGÍA = "2513 BIOLOGÍA",
	ESTADÍSTICA = "2514 ESTADÍSTICA",
	FARMACIA = "2515 FARMACIA",
	FÍSICA = "2516 FÍSICA",
	GEOLOGÍA = "2517 GEOLOGÍA",
	MATEMÁTICAS = "2518 MATEMÁTICAS",
	QUÍMICA = "2519 QUÍMICA",
	CC = "2933 CIENCIAS DE LA COMPUTACIÓN",
}

/**
 * Economical Science faculty (2051) programs
 */
export enum eSIAEconomicalScienceBogotaProgram {
	CONTADURÍA_PÚBLICA = "2521 CONTADURÍA PÚBLICA",
	ECONOMÍA = "2522 ECONOMÍA",
	ADMINISTRACIÓN_DE_EMPRESAS = "2A41 ADMINISTRACIÓN DE EMPRESAS",
}

/**
 * Human Science faculty (2052) programs
 */
export enum eSIAHumanScienceBogotaProgram {
	ANTROPOLOGÍA = "2523 ANTROPOLOGÍA",
	FILOLOGÍA_E_IDIOMAS_ALEMÁN = "2524 FILOLOGÍA E IDIOMAS ALEMÁN",
	FILOLOGÍA_E_IDIOMAS_FRANCÉS = "2525 FILOLOGÍA E IDIOMAS FRANCÉS",
	ESPAÑOL_Y_FILOLOGÍA_CLÁSICA = "2526 ESPAÑOL Y FILOLOGÍA CLÁSICA",
	FILOLOGÍA_E_IDIOMAS_INGLÉS = "2527 FILOLOGÍA E IDIOMAS INGLÉS",
	GEOGRAFÍA = "2531 GEOGRAFÍA",
	HISTORIA = "2532 HISTORIA",
	ESTUDIOS_LITERARIOS = "2534 ESTUDIOS LITERARIOS",
	SOCIOLOGÍA = "2536 SOCIOLOGÍA",
	TRABAJO_SOCIAL = "2537 TRABAJO SOCIAL",
	LINGÜÍSTICA = "2837 LINGÜÍSTICA",
	PSICOLOGÍA = "2977 PSICOLOGÍA",
	FILOSOFÍA = "2997 FILOSOFÍA",
}

/**
 * Agronomical Science faculty (2728) programs
 */
export enum eSIAAgronomicalScienceBogotaProgram {
	INGENIERÍA_AGRONÓMICA = "2505 INGENIERÍA AGRONÓMICA",
}

export type uSIABogotaProgram =
	| eSIABogotaProgram
	| eSIAMedicineBogotaProgram
	| eSIAVetMedicineBogotaProgram
	| eSIAEnfermeryBogotaProgram
	| eSIAArtsBogotaProgram
	| eSIAEngineeringBogotaProgram
	| eSIAOdontologyBogotaProgram
	| eSIALawBogotaProgram
	| eSIAScienceBogotaProgram
	| eSIAEconomicalScienceBogotaProgram
	| eSIAHumanScienceBogotaProgram
	| eSIAAgronomicalScienceBogotaProgram;
