/**
 * Manizales faculties.
 *
 * Manizales is its own faculty for global courses.
 */
export enum eSIAManizalesFaculty {
	SEDE_MANIZALES = "4000 SEDE MANIZALES",
	FACULTAD_DE_INGENIERIA_Y_ARQUITECTURA = "4036 FACULTAD DE INGENIERIA Y ARQUITECTURA",
	FACULTAD_DE_CIENCIAS_EXACTAS_Y_NATURALES = "4037 FACULTAD DE CIENCIAS EXACTAS Y NATURALES",
	FACULTAD_DE_ADMINISTRACIÓN = "4046 FACULTAD DE ADMINISTRACIÓN",
}

/**
 * Manizales global (4000) programs
 */
export enum eSIAManizalesProgram {
	MEDICINA_VETERINARIA = "2555 MEDICINA VETERINARIA",
	ESTADÍSTICA = "3504 ESTADÍSTICA",
	INGENIERÍA_BIOLÓGICA = "3505 INGENIERÍA BIOLÓGICA",
	COMPONENTE_DE_LIBRE_ELECCIÓN = "4CLE COMPONENTE DE LIBRE ELECCIÓN",
	COMPONENTE_ELEGIBLE_POSGRADO = "4CLP COMPONENTE ELEGIBLE POSGRADO",
	CRÉDITOS_PRIMER_PLAN_PARA_DOBLE_TITULACIÓN = "4DTS CRÉDITOS PRIMER PLAN PARA DOBLE TITULACIÓN",
	PROGRAMA_ELECTIVAS_SEDE_MANIZALES = "ZEMZ PROGRAMA ELECTIVAS SEDE MANIZALES",
}

/**
 * Engineering and Architecture faculty (4036) programs
 */
export enum eSIAEngineeringAndArchitectureManizalesProgram {
	INGENIERIA_CIVIL = "4021 INGENIERIA CIVIL",
	INGENIERIA_ELECTRICA = "4022 INGENIERIA ELECTRICA",
	INGENIERIA_QUIMICA = "4023 INGENIERIA QUIMICA",
	INGENIERIA_INDUSTRIAL = "4024 INGENIERIA INDUSTRIAL",
	ARQUITECTURA = "4025 ARQUITECTURA",
	INGENIERIA_ELECTRONICA = "4028 INGENIERIA ELECTRONICA",
	CONSTRUCCION = "4031 CONSTRUCCION",
}

/**
 * Exact and natural sciences  (4037) programs
 */
export enum eSIAExactSciencesManizalesProgram {
	INGENIERIA_FISICA = "4030 INGENIERIA FISICA",
	MATEMATICAS = "4032 MATEMATICAS",
	CIENCIAS_DE_LA_COMPUTACIÓN = "4034 CIENCIAS DE LA COMPUTACIÓN",
	ESTADÍSTICA = "4036 Estadística",
	INGENIERÍA_BIOLÓGICA = "4037 Ingeniería Biológica",
}

/**
 * Management (4046) programs
 */
export enum eSIAManagementManizalesProgram {
	GESTION_CULTURAL_Y_COMUNICATIVA = "4033 GESTION CULTURAL Y COMUNICATIVA",
	ADMINISTRACION_DE_EMPRESAS_D = "4026 ADMINISTRACION DE EMPRESAS (D)",
	ADMINISTRACION_DE_EMPRESAS_N = "4027 ADMINISTRACION DE EMPRESAS (N)",
	ADMINISTRACION_DE_SISTEMAS_INFORMATICOS_A = "4029 ADMINISTRACION DE SISTEMAS INFORMATICOS",
	ADMINISTRACION_DE_SISTEMAS_INFORMATICOS_B = "4035 ADMINISTRACION DE SISTEMAS INFORMATICOS",
}

export const eSIAManizalesPrograms = {
	// ...eSIAManizalesProgram,
	...eSIAEngineeringAndArchitectureManizalesProgram,
	...eSIAExactSciencesManizalesProgram,
	...eSIAManagementManizalesProgram,
} as const;

export type uSIAManizalesProgram =
	| eSIAManizalesProgram
	| eSIAEngineeringAndArchitectureManizalesProgram
	| eSIAExactSciencesManizalesProgram
	| eSIAManagementManizalesProgram;
