import { eSIAEnfermeryBogotaProgram, eSIAScienceBogotaProgram } from "./bogota.js";

/**
 * Medellín faculties.
 *
 * Medellín is its own faculty for global courses.
 */
export enum eSIAMedellinFaculty {
	SEDE_MEDELLÍN = "3 SEDE MEDELLÍN",
	FACULTAD_DE_MINAS = "3068 FACULTAD DE MINAS",
	FACULTAD_DE_ARQUITECTURA = "3064 FACULTAD DE ARQUITECTURA",
	FACULTAD_DE_CIENCIAS = "3065 FACULTAD DE CIENCIAS",
	FACULTAD_DE_CIENCIAS_AGRARIAS = "3442 FACULTAD DE CIENCIAS AGRARIAS",
	FACULTAD_DE_CIENCIAS_HUMANAS_Y_ECONÓMICAS_A = "3067 FACULTAD DE CIENCIAS HUMANAS  Y ECONÓMICAS",
	FACULTAD_DE_CIENCIAS_HUMANAS_Y_ECONÓMICAS_B = "3067 FACULTAD DE CIENCIAS HUMANAS Y ECONÓMICAS",
}

/**
 * Medellín global (3) programs
 */
export enum eSIAMedellinProgram {
	FARMACIA = eSIAScienceBogotaProgram.FARMACIA,
	ENFERMERÍA = eSIAEnfermeryBogotaProgram.ENFERMERÍA,
	COMPONENTE_DE_LIBRE_ELECCIÓN = "3CLE COMPONENTE DE LIBRE ELECCIÓN",
	COMPONENTE_ELEGIBLE_POSGRADO = "3CLP COMPONENTE ELEGIBLE POSGRADO",
}

/**
 * Mines faculty (3068) programs
 */
export enum eSIAMinesMedellinProgram {
	INGENIERÍA_ADMINISTRATIVA_A = "3515 INGENIERÍA ADMINISTRATIVA",
	INGENIERÍA_ADMINISTRATIVA_B = "3528 INGENIERÍA ADMINISTRATIVA",
	INGENIERÍA_AMBIENTAL_A = "3527 INGENIERÍA AMBIENTAL",
	INGENIERÍA_AMBIENTAL_B = "3529 INGENIERÍA AMBIENTAL",
	INGENIERÍA_CIVIL = "3516 INGENIERÍA CIVIL",
	INGENIERÍA_CIVIL_B = "3530 INGENIERÍA CIVIL",
	INGENIERÍA_DE_CONTROL_A = "3517 INGENIERÍA DE CONTROL",
	INGENIERÍA_DE_CONTROL_B = "3531 INGENIERÍA DE CONTROL",
	INGENIERÍA_DE_MINAS_Y_METALURGIA_A = "3518 INGENIERÍA DE MINAS Y METALURGIA",
	INGENIERÍA_DE_MINAS_Y_METALURGIA_B = "3532 INGENIERÍA DE MINAS Y METALURGIA",
	INGENIERÍA_DE_PETRÓLEOS_A = "3519 INGENIERÍA DE PETRÓLEOS",
	INGENIERÍA_DE_PETRÓLEOS_B = "3533 INGENIERÍA DE PETRÓLEOS",
	INGENIERÍA_DE_SISTEMAS_E_INFORMÁTICA_A = "3520 INGENIERÍA DE SISTEMAS E INFORMÁTICA",
	INGENIERÍA_DE_SISTEMAS_E_INFORMÁTICA_B = "3534 INGENIERÍA DE SISTEMAS E INFORMÁTICA",
	INGENIERÍA_ELÉCTRICA_A = "3521 INGENIERÍA ELÉCTRICA",
	INGENIERÍA_ELÉCTRICA_B = "3535 INGENIERÍA ELÉCTRICA",
	INGENIERÍA_GEOLÓGICA_A = "3522 INGENIERÍA GEOLÓGICA",
	INGENIERÍA_GEOLÓGICA_B = "3536 INGENIERÍA GEOLÓGICA",
	INGENIERÍA_INDUSTRIAL_A = "3523 INGENIERÍA INDUSTRIAL",
	INGENIERÍA_INDUSTRIAL_B = "3537 INGENIERÍA INDUSTRIAL",
	INGENIERÍA_MECÁNICA_A = "3524 INGENIERÍA MECÁNICA",
	INGENIERÍA_MECÁNICA_B = "3538 INGENIERÍA MECÁNICA",
	INGENIERÍA_QUÍMICA_A = "3525 INGENIERÍA QUÍMICA",
	INGENIERÍA_QUÍMICA_B = "3539 INGENIERÍA QUÍMICA",
}

/**
 * Architecture faculty (3064) programs
 */
export enum eSIAArchitectureMedellinProgram {
	ARQUITECTURA = "3501 ARQUITECTURA",
	ARTES_PLÁSTICAS = "3502 ARTES PLÁSTICAS",
	CONSTRUCCIÓN = "3503 CONSTRUCCIÓN",
}

/**
 * Science faculty (3065) programs
 */
export enum eSIAScienceMedellinProgram {
	ESTADÍSTICA = "3504 ESTADÍSTICA",
	INGENIERÍA_BIOLÓGICA = "3505 INGENIERÍA BIOLÓGICA",
	INGENIERÍA_FÍSICA = "3506 INGENIERÍA FÍSICA",
	MATEMÁTICAS = "3507 MATEMÁTICAS",
	CIENCIAS_DE_LA_COMPUTACIÓN = "3647 CIENCIAS DE LA COMPUTACIÓN",
	QUÍMICA = "3705 QUÍMICA",
}

/**
 * Agrarian sciences faculty (3442) programs
 */
export enum eSIAAgrarianSciencesMedellinProgram {
	INGENIERÍA_AGRÍCOLA = "3508 INGENIERÍA AGRÍCOLA",
	INGENIERÍA_AGRONÓMICA = "3509 INGENIERÍA AGRONÓMICA",
	INGENIERÍA_FORESTAL = "3510 INGENIERÍA FORESTAL",
	ZOOTECNIA = "3511 ZOOTECNIA",
}

/**
 * Human sciences A faculty (3067) programs
 * There is a B without a typo, but no programs
 */
export enum eSIAHumanSciencesAMedellinProgram {
	CIENCIA_POLÍTICA = "3512 CIENCIA POLÍTICA",
	ECONOMÍA = "3513 ECONOMÍA",
	HISTORIA = "3514 HISTORIA",
}

export const eSIAMedellinPrograms = {
	// ...eSIAMedellinProgram,
	...eSIAMinesMedellinProgram,
	...eSIAArchitectureMedellinProgram,
	...eSIAScienceMedellinProgram,
	...eSIAAgrarianSciencesMedellinProgram,
	...eSIAHumanSciencesAMedellinProgram,
} as const;

export type uSIAMedellinProgram =
	| eSIAMedellinProgram
	| eSIAMinesMedellinProgram
	| eSIAArchitectureMedellinProgram
	| eSIAScienceMedellinProgram
	| eSIAAgrarianSciencesMedellinProgram
	| eSIAHumanSciencesAMedellinProgram;
